### ISSUE TITLE
Error Socks5

### ISSUE THREAD

**Issue by Jakeypinty** [blacklanternsecurity/TREVORspray#25]
![image](https://user-images.githubusercontent.com/104181541/210067840-b55d9ae2-2adb-4180-a5f1-8f2c68802be4.png)

Updated Kali to the newest version 6.0.0, now im getting this error? In the past I believe it was my own syntax causing the issue but now I cannot work out the problem.

[ERRR] Traceback (most recent call last):
  File "/home/kali/Tools/TREVORspray/trevorspray/./cli.py", line 155, in main
    sprayer = TrevorSpray(options)
  File "/home/kali/Tools/TREVORspray/trevorspray/lib/trevor.py", line 59, in __init__
    proxy = ProxyThread(
  File "/home/kali/Tools/TREVORspray/trevorspray/lib/proxy.py", line 70, in __init__
    self.proxy.start()
  File "/home/kali/.local/lib/python3.10/site-packages/trevorproxy/lib/ssh.py", line 62, in start
    raise SSHProxyError(f'Failed to start SSHProxy {self}')
trevorproxy.lib.errors.SSHProxyError: Failed to start SSHProxy socks5://127.0.0.1:33482

**Comment by Synzack** [comment]
I had the same issue. Turned out it was permissions on my SSH key. Try SSH-ing manually and see if theres any errors.

**Comment by TheTechromancer** [comment]
Added a more helpful error message in TREVORproxy: https://github.com/blacklanternsecurity/TREVORproxy/commit/0e061627c1e0713c84fdc9cf2bf59f686bcb4f53
